### ISSUE TITLE
docs error & other stuff

### ISSUE THREAD

**Issue by jmls** [stormpath/stormpath-sdk-node#126]
http://docs.stormpath.com/nodejs/api/directory#createGroup

has a couple of errors (I think!)

*directory.createGroup(group, onGroupCreation(err, createdGroup) {
  console.log(createdGroup);
});*

should be

*directory.createGroup(group*, **function** *onGroupCreation(err, createdGroup) {
  console.log(createdGroup);
});*

and 

*directory.createGroup(group, {expand:'directory'}, function onAccountCreated(err, createdGroup) {
  console.log(createdGroup);
});*

should be

*directory.createGroup(group, {expand:'directory'}, function* **onGroupCreated** *(err, createdGroup) {
  console.log(createdGroup);

you should also probably be consistent  and call the function either **onGroupCreation** or **onGroupCreated** but not both ;)
});*

**Comment by rdegges** [comment]
We'll get this fixed next week during our pairing session =) Thanks for the infos!

**Comment by rdegges** [comment]
Ok, finally got around to fixing this. The docs have been updated, and a PR has been made: https://github.com/stormpath/stormpath.github.io/pull/183

This is officially closed!
