### ISSUE TITLE
Approved/Recommended way to handle authenticateAccount result

### ISSUE THREAD

**Issue by philipatkinson** [stormpath/stormpath-sdk-node#130]
There is a slight difference in the official docs about how to handle the successful result from authenticateAccount. In the main [NodeJS](http://docs.stormpath.com/nodejs/quickstart/#authenticate-a-user-account) docs, the returned account object is accessed directly:

```
app.authenticateAccount({
  username: 'tk421@stormpath.com',
  password: 'Changeme1',
}, function (err, result) {
  if (err) throw err;
  account = result.account;
});
account.givenName

```

Whereas in the API docs and sdk the result is passed to getAccount:

```
createdApp.authenticateAccount(authcRequest, function onAuthcResult(err, result) {

  //if successful, you can obtain the account by calling result.getAccount:

  return result.getAccount(function(err2, account) { //this is cached and will execute immediately (no server request):
    if(err) throw err;
    console.log(account);
  });
});

```
At the moment, the getAccount route generates a number of extra cache calls, which would appear to be a less efficient method. Which is the approved method of accessing an account after authenticateAccount?

**Comment by rdegges** [comment]
This has been fixed in our docs, so closing this out. Thanks @philipatkinson for the report.
