### ISSUE TITLE
Module Bloat

### ISSUE THREAD

**Issue by coreybutler** [stormpath/stormpath-sdk-node#141]
I was looking at the module after a simple `npm install stormpath` and I noticed the directory contains `docs`, & `samples`. Is this really necessary to ship in the node module? I am using this in a lot of places, meaning I have lots of copies of the same documentation I'll never read (I'll use the website instead) needlessly clogging up my server.

For that matter, I don't think the tests are necessary, the .travis.yml, example scripts in the root directory. Bottom line is it's a mess for deploying to production. I can see how this makes sense if you're learning about the library, perhaps running a "git clone" to familiarize... but this is... needless in production.

Perhaps the `.npmignore` could be updated to not push all of this extra stuff to npm?

**Comment by robertjd** [comment]
Thanks @coreybutler - good idea.  I just published 0.9.1 with .npmignore

**Comment by coreybutler** [comment]
@robertjd - Awesome... kudos for such quick turnaround!

**Comment by robertjd** [comment]
no prob!
