### ISSUE TITLE
Document Application.resendVerificationEmail()

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-node#142]
We currently have no documentation for `Application.resendVerificationEmail()` -- but we should!

**Comment by ryneo** [comment]
+1

**Comment by dlai0001** [comment]
:+1

**Comment by robertjd** [comment]
Hi there, we're currently re-writing this module documentation with JSDoc, so all the things will be documented :)

The method `Application.resendVerificationEmail()` takes `({email: 'foo@bar.com},callback)` as arguments.

And yes, you can reset an account's password manually by getting the account, changing the password property, then calling the `save()` method on the account.

**Comment by christophersw** [comment]
Small correction - it looks like the method 
```
Application.resendVerificationEmail()
```
actually takes **login** not **email**. 

```
({login: 'foo@bar.com'}, callback)
```

Also +1 for adding this to the documentation!

**Comment by robertjd** [comment]
This has been done.
