### ISSUE TITLE
Broken example in quickstart guide

### ISSUE THREAD

**Issue by luyizhao** [stormpath/stormpath-sdk-node#145]
Seems to be a broken example at: http://docs.stormpath.com/nodejs/quickstart/#search-for-a-user-account. (quickstart codeblock shown below)

```javascript
app.getAccounts({email: 'tk421@stormpath.com'}, function(err, accounts) {
  if (err) throw err;
  accounts.each(function (err, account, index) {
    console.log(account.givenName + " " + account.surname);
  });
});
```

```.each()``` iIterator function on the ```accounts``` CollectionsResource object appears to be incorrect. Think it should read something like this:

```javascript
accounts.each(function (account) {
    console.log(account.givenName + " " + account.surname);
  }, function(err){ 
    // handle errors in the callback
  });
```

**Comment by robertjd** [comment]
Thanks for finding this, marking as docs for my next pass.  You're right, the callback of the iterator is `(resource,next)` - it's mimicking the caolan/async library

**Comment by rdegges** [comment]
Closing this as I've updated all the docs =)
