### ISSUE TITLE
API Docs with JSDOC

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-node#149]
It'd be nice to have JSdoc builds for our API docs. Not this custom stuffz that is hard to maintain.

**Comment by typerandom** [comment]
@rdegges Is this still something that we want? Or can we close it? :)

**Comment by robertjd** [comment]
We do want to move to JS Docs

**Comment by robertjd** [comment]
These docs are now online here: http://docs.stormpath.com/nodejs/jsdoc/
