### ISSUE TITLE
OAuth TTL Not Respected

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-node#153]
Just got a user report that the Oauth TTL settings are not taking effect: https://github.com/stormpath/stormpath-sdk-node/blob/master/lib/authc/OAuthBasicExchangeAuthenticator.js#L21

No matter what, it's defaulting to 1 hour (in seconds).

**Comment by syonip** [comment]
Hey, any progress on this issue?
Currently this is forcing mobile apps to use loginRequired instead of apiAuthenticationRequired.
Do you have a workaround perhaps?

**Comment by robertjd** [comment]
Hi @syonip can you show me how you're passing the option?  Here's how the library expects the option to be passed:

```
app.authenticateApiRequest({
  request: requestObject,
  ttl: desiredTtl
},function(err,authenticationResult){
  //callback
});
```

Here is our test case which asserts that the TTL is being set on tokens:

https://github.com/stormpath/stormpath-sdk-node/blob/master/test/it/api_auth_it.js#L601-L637

**Comment by syonip** [comment]
Hi @robertjd, I'm using the stormpath.init method:

self.app.use(stormpath.init(self.app, {
      loginView: __dirname + '/server/login-views/login.jade',
      apiKeyFile: 'server/apiKey.properties',
      application: conf.settings.stormpath_url,
      secretKey: conf.settings.stormpath_secret,
      enableForgotPassword: true,
      enableGivenName: false,
      requireGiveName: false,
      enableSurname: false,
      requireSurname: false,
      postRegistrationHandler: newUser,
      sessionDuration: 1000 * 60 * 60 * 24 * 30,  // 30 days +-
      oauthTTL: 60 * 60 * 24 * 30 * 6 // 6 months, for mobile app
    }));

**Comment by robertjd** [comment]
Ah!  In that case this is an issue with the [stormpath-express](https://github.com/stormpath/stormpath-express) module, we should bring the issue over there.  Ping @rdegges

**Comment by syonip** [comment]
Hey, can't seem to get through to @rdegges.
What's the preferred way of pinging him?

**Comment by lhazlewood** [comment]
Mentioning him as you did via @rdegges - he's good about answering GitHub mentions.  He's traveling to PyCon this week and might not be readily accessible until Monday.

**Comment by syonip** [comment]
That's cool, thanks.

**Comment by rdegges** [comment]
Hey @all =)

Just looking at this. Here's what I know so far about this regarding the express-stormpath library (brain dump here):

- There is a setting called `stormpathOauthTTL` that is defined like so:  https://github.com/stormpath/stormpath-express/blob/master/lib/settings.js#L74
- This setting is only used in one place in the library, which is here: https://github.com/stormpath/stormpath-express/blob/15dd7bf88f5e9be3e7dbbb33c21680f2bf534624/lib/controllers.js#L553-566

The exact code snippet used is:

```javascript
    req.app.get('stormpathApplication').authenticateApiRequest({
      request: req,
      ttl: req.app.get('stormpathOauthTTL'),
      scopeFactory: function(account, requestedScopes) {
        return requestedScopes;
      }
    }, function(err, authResult) {
      if (err) {
        res.json(503, { error: 'Something went wrong. Please try again.' });
        req.app.get('stormpathLogger').info('An OAuth token exchange failed due to an improperly formed request.');
      } else {
        res.json(authResult.tokenResponse);
      }
    });
```

This looks like the correct usage to me.

Furthermore, if I build a test application and generate a JWT using the above controller, I get back a token with the proper expiration time set.

So, this doesn't look like there's any problem to me.

Here's a full app I created to demo this:

```javascript
var express = require('express');
var stormpath = require('express-stormpath');

var app = express();

app.use(stormpath.init(app, {
  oauthTTL: 3700,  // note, 3700 is the expiration time
  application: 'https://api.stormpath.com/v1/applications/xxx',
  apiKeyId: 'xxx',
  apiKeySecret: 'xxx'
}));

app.listen(3000);
```

Here's what I get when I perform a token exchange via curl:

```console
$ curl -vX POST --user 'xxx:xxx' 'http://127.0.0.1:3000/oauth?grant_type=client_credentials'
{"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1VEo3QUk4WVpFWktUNVA1QVlOQjlTUkpZIiwiaXNzIjoiaHR0cHM6Ly9hcGkuc3Rvcm1wYXRoLmNvbS92MS9hcHBsaWNhdGlvbnMvMWFXRnkwQlB6dVlXWUxZTTJxa3pjZiIsImlhdCI6MTQyOTIyMDk5NCwiZXhwIjoxNDI5MjI0Njk0LCJzY29wZSI6IiJ9.J2FZ_9kRWF3v4s1v5QUE4dzksa4XDo-TqOsoGYCu29c","token_type":"bearer","expires_in":3700,"scope":""}
```

Notice the `expires_in` value of `3700` above? That all checks out.

@syonip how did you produce this? EG: When you get back your JWT -- how do you know the timeout is occuring early? I plugged mine into

**Comment by rdegges** [comment]
Closing this since can't reproduce.
