### ISSUE TITLE
Update request dependency

### ISSUE THREAD

**Issue by coreybutler** [stormpath/stormpath-sdk-node#154]
I'd like to request an update to the request dependency, to version 2.53.0 (unless 2.53.1 is released by the time this is read).

There were some breaking changes in node 0.12 that [affected the request module](https://github.com/request/request/blob/e76691996b92d1fb4bdfe96a3a6d8527d02d053b/README.md#-does-not-work-with-node-v012x-). These appear to be resolved in newer versions. The current `package.json` forces an older version of request, and I noticed the travis tests do not yet include node 0.12.

I cloned the repo and ran the tests against node 0.12 with 21 failures, primarily cutting out after the Istanbul coverage tests. I think the errors are more likely a result of my configuration, but it might be worth looking into. Most of them had to do with pulling resources by `href`.

Anyhow, either updating the dependency to use request `~2.53.0` or `^2.40.0` should do the trick. I'm happy to submit a PR on this if you want, but since it's such a simple change with a choice, I figured I'd leave it to you guys.

**Comment by rdegges** [comment]
Thanks for the report, taking care of this now.

**Comment by rdegges** [comment]
Hmm, apparently 2.53.0 breaks our mocks (using Nock):

```
1) Resources:  InstanceResource class call to get resource with optional query and ctor param "before all" hook:
     Uncaught Error: Nock: No match for HTTP request GET /v1/href?q=boom%21
      at RequestOverrider.end (/Users/rdegges/Dropbox/Code/stormpath/stormpath-sdk-node/node_modules/nock/lib/request_overrider.js:170:13)
      at OverridenClientRequest.RequestOverrider.req.end (/Users/rdegges/Dropbox/Code/stormpath/stormpath-sdk-node/node_modules/nock/lib/request_overrider.js:109:7)
      at Request.end (/Users/rdegges/Dropbox/Code/stormpath/stormpath-sdk-node/node_modules/request/request.js:1637:12)
      at end (/Users/rdegges/Dropbox/Code/stormpath/stormpath-sdk-node/node_modules/request/request.js:676:14)
      at Object._onImmediate (/Users/rdegges/Dropbox/Code/stormpath/stormpath-sdk-node/node_modules/request/request.js:690:7)
      at processImmediate [as _immediateCallback] (timers.js:336:15)
```

Will need to figure this out before cutting a new release with the updated version of request.

**Comment by rdegges** [comment]
Anyone got any idea how to fix this? I've been trying to make this work, but haven't been able to figure anything out or make any progress on this >.>

**Comment by robertjd** [comment]
My preference is to stop using nock, I started working on that here (turning the nock based tests into actual unit tests):

https://github.com/robertjd/stormpath-sdk-node/commit/7566e952acef0994d89ddcbd596ece8538ebfe72

**Comment by typerandom** [comment]
@robertjd What is the status on this? Can we close it?

**Comment by robertjd** [comment]
We should upgrade this, but the above test is still a problem that needs to be fixed

**Comment by typerandom** [comment]
Closing this since we're now using the one of the latest request releases (v2.67.0):

https://github.com/request/request/releases
https://github.com/stormpath/stormpath-sdk-node/blob/master/package.json#L56
