### ISSUE TITLE
Fix Node Compat Issues

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-node#155]
Right now it appears that we're unable to support Node 0.11.x, 0.12.x, iojs, or iojs-1.0.4: https://travis-ci.org/stormpath/stormpath-sdk-node/builds/55584047

I think we should fix / clean up these issues so we can expand our userbase beyond 0.10.x.

**Comment by francisdb** [comment]
No progress on this?

**Comment by rdegges** [comment]
We haven't been working on this yet -- been busy implementing some new configuration format. We'll be getting to this once the next release has been cut though!

**Comment by rdegges** [comment]
Working on this now -- the issue is that one of the underlying libraries for testing isn't compatible. I can fix this by getting rid of these extra tests, I think.

**Comment by rdegges** [comment]
Will update this issue as I make progress.

**Comment by rdegges** [comment]
Might be easier than I thought -- there are only a few tests written in a way which prevents upgrading. I'm going to comment these out for now, test on all versions of node > 0.10, then cut a release. We can backport these into our IT tests in the future.

**Comment by rdegges** [comment]
Ok, cutting a new release now (0.11.3), which is fully compatible with 0.11, 0.12, and iojs =)

**Comment by rdegges** [comment]
Ok, release cut. All good to go!
