### ISSUE TITLE
Stormpath-Linkedin-oAuth2 Support

### ISSUE THREAD

**Issue by debasha** [stormpath/stormpath-sdk-node#159]
HI,
I'd like to request an update to the current version where Linkedin Login support would be provided using oAuth2.

**Comment by robertjd** [comment]
Hi @debasha !

Have you run into a problem with our Linkedin integration?  We do support Linkedin as one of our directory types, which are agnostic to the mechanism by when you obtain the Linkedin access token from the user (this happens in your front-end application, or via page-based callbacks on your server).  

Once you have that token, you should supply it to the [Application.getAccount](http://docs.stormpath.com/nodejs/api/application#getAccount) method as the `accessToken` property, and using `'linkedin'` as the `prodiverId`.

I hope this helps!

**Comment by typerandom** [comment]
Closing issue since it's old and hasn't been updated since May. Reopen if issue still persists.
