### ISSUE TITLE
Improve Custom Data Saving

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-node#161]
Right now if you modify customData, you have to say:

```javascript
req.user.customData.save();
```

In order to trigger the updates. It would be nice if we could simply say:

```javascript
req.user.save();
```

To trigger both normal user field updates as well as customData updates.

**Comment by cwhatley** [comment]
I'm actually seeing behavior where I modify custom data and then do req.user.save() and on the next request, the custom data is not available in req.user, but it does show up in the stormpath console.

When I do req.user.customData.save(), then on the next request, I do see my custom data in req.user.

**Comment by rdegges** [comment]
This is a known issue -- we're working on a plan to get this resolved =)

**Comment by robertjd** [comment]
This was a bug in the Express module, which appears to be resolved.  Closing.
