### ISSUE TITLE
No Method 'authenticateAccount'

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-node#164]
Hi all,

I've seen this several times, but we've got more reports of users receiving errors like the following:

```console
> Object https://api.stormpath.com/v1/applications/xxx has no method 'authenticateAccount'
```

This is related to the issue where after making requests (*I'm not sure how to reproduce this yet*), the returned object has no `href` property.

**Comment by maceip** [comment]
I'm using express-stormpath 1.0.4 on Azure and I'm seeing this bug on every single API request.

I'm even using the code published on the blog here:

And I'm using this curl command:

```
curl -v --user 'USERID:SECRET' -H 'Content-Type: application/json' --data '{"phoneNumber": "+18882223333"}' 'http://SITE.azurewebsites.net/api/message/'
```

```
TypeError: Object https://api.stormpath.com/v1/applications/OUa93OlBibXbDxstnOVwA/ has no method 'authenticateApiRequest'
    at Object.module.exports.getUser (D:\home\site\wwwroot\node_modules\express-stormpath\lib\helpers.js:263:41)
```

**Comment by lhazlewood** [comment]
I'm not sure why there is a `/` at the end of the uri - there isn't supposed to be one.

Instead of this: 

`https://api.stormpath.com/v1/applications/APPID/`

it should be:

`https://api.stormpath.com/v1/applications/APPID`

I'm not sure if this is related at all but I thought I'd point it out.

**Comment by maceip** [comment]
I tried it without the trailing slash and am getting the same error.

**Comment by typerandom** [comment]
@rdegges @maceip Is this still an issue, or can we close it?

**Comment by robertjd** [comment]
I'm going to close this, please re-open if the problem persists.  Please note that the 2.x series is the latest version of this library, and has likely resolved this problem.
