### ISSUE TITLE
AuthRequestParser incorrectly accepting null body

### ISSUE THREAD

**Issue by bbarr** [stormpath/stormpath-sdk-node#170]
```javascript  
var body = typeof req.body === 'object' ? req.body : {};
```
Koa.js appears to assign ```null``` for the body on GET requests, so in Javascript's infinite wisdom, that makes it an "object". 

Perhaps
```javascript
var body =  typeof req.body === 'object' && req.body !== null ? req.body : {}
```
will cover your intended condition more completely.

Thanks!

**Comment by robertjd** [comment]
Thanks for the report!  Have you been able to work around this problem?

**Comment by rdegges** [comment]
Ok, just fixed this -- also added tests and improved validation for other parts of this validator =)

Closing this out. It will be in the next release (0.11.3).
