### ISSUE TITLE
scopeFactory with asynchronous code to decide scopes

### ISSUE THREAD

**Issue by bbarr** [stormpath/stormpath-sdk-node#171]
I am very confused on this one. Stormpath suggests you use groups to determine some scopes, but then the only way to access groups is by async request, so, we have:

```
scopeFactory(account, requestedScope) {
  account.getGroups((e, groups) => ... too late!)
  return [ 'useless', 'scope' ]
}
```

I know I am missing something here.. can I somehow get groups baked into the account on the original request? Or, perhaps something else?

Thanks!

**Comment by rdegges** [comment]
Hi @bbar, thanks for reporting this! We'll get this fixed so that you can use proper async stuff inside the scope factory -- this was an oversight on our part during the initial design -- so we'll get that fixed =)

Sorry about the issues!

We'll post some updates to this issue once we get going.

-R

**Comment by robertjd** [comment]
Yes this was an unforunate mistake :(

To work around the issue, the `autenticateApiRequest` method is giving you an instance of an `AuthenticationResult`, which has a `getJwt` method.  You can use that method to get the un-compacted JWT and then modify it's body (such as the scope field) before compacting it into an access token.  Documentation is here:

http://docs.stormpath.com/nodejs/api/authenticationResult#authenticateApiRequest

**Comment by robertjd** [comment]
Adding this to the next minor release.  We should add the ability to return scopes async, without breaking the current sync functionality.
