### ISSUE TITLE
Enable Node SDK to handle new ID Site error callbacks

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-node#178]
Internal Spec:
https://stormpath.atlassian.net/wiki/display/AM/Error+Callback+for+ID+Site

**Comment by typerandom** [comment]
@omgitstom I'm having trouble seeing exactly what needs to be done here. It seems like [the feature is already implemented](https://github.com/stormpath/stormpath-sdk-node/blob/master/lib/resource/Application.js#L79) and from looking at the current implementation and comparing it to the spec I'm not seeing any clear changes.

**Comment by robertjd** [comment]
This is already implemented.
