### ISSUE TITLE
Support Options for Application.authenticateAccount()

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-node#184]
https://github.com/stormpath/stormpath-sdk-node/blob/master/lib/resource/Application.js#L117

We should support the passing of options here. I thought? we did this previously, but didn't see anything in `git blame`, so I guess I must be going crazy.

This functionality would allow developers to expand groups, customData, etc. during authentication.

**Comment by robertjd** [comment]
The only supported parameter for this API endpoint is the expansion of the account (you can't do a second expand do expand group resources).  This is an API limitation.  This method is hard coded to always expand the account:

https://github.com/stormpath/stormpath-sdk-node/blob/master/lib/resource/Application.js#L137
