### ISSUE TITLE
fs.existsSync deprecated

### ISSUE THREAD

**Issue by christophersw** [stormpath/stormpath-sdk-node#197]
According to [Node Docs](https://nodejs.org/api/fs.html#fs_fs_existssync_path), fs.existsSync is deprecated and fs.statSync or fs.accessSync should be used instead.

This impacts [/lib/Config.js line 21](https://github.com/stormpath/stormpath-sdk-node/blob/cfd73d93aee7ecc1174202cc6fc33cf443529e1a/lib/Config.js#L21) 

```javascript
...
var userConfig = fs.existsSync(userConfigPath) ?
...
```

This seems to be causing an error on the latest version of node. I am getting error: "no method 'existsSync'" when using node version 0.12.7 ...

**Comment by typerandom** [comment]
Closing since this has been resolved by PR #213.
