### ISSUE TITLE
getAccessToken() default TTL value is incorrectly set as 3600ms (expected 3600s)

### ISSUE THREAD

**Issue by ck-lee** [stormpath/stormpath-sdk-node#204]
When `getAccessToken()` method is called, the `expires_in` value is incorrectly set.
This is due to `nJwt.setExpiration()` expects values in _milliseconds_. Not _seconds_

Also noticed that `jwt.ttl` value is not set by nJwt library.

**Comment by robertjd** [comment]
Fixed by #214
