### ISSUE TITLE
Having stormpath.json in catalog results in exception

### ISSUE THREAD

**Issue by vgoloviznin** [stormpath/stormpath-sdk-node#207]
If I have a `stormpath.json` file in the root of my nodejs application, requiring stormpath results in exception. 

```
throw new TypeError('must start with number, buffer, array or string');
```

I'm running windows 10, nodejs 4.0, stormpath version 0.12.0

As I've found out the issue is here in `Config.js` file here : 

```
var currentConfig = fs.existsSync(currentConfigPath) ?
  fs.readSync(currentConfigPath) : {};
```

As `readSync` expects a buffer and not a string, so using `readFileSync` should do the job of reading settings

**Comment by typerandom** [comment]
Closing issue since this should have been resolved by PR #213.
