### ISSUE TITLE
Error getting JwtAuthenticationResult account info on JwtAuthenticationResult when using local validation

### ISSUE THREAD

**Issue by asargento** [stormpath/stormpath-sdk-node#227]
When using local validation, getting the account from authentication result can not be done as follows (account is not defined).
```javascript
JwtAuthenticationResult.prototype.getAccount = function getAccount(callback) {
  // workaround because I don't have access to a stormpath client
  this.application.dataStore.getResource(this.account.href, require('../resource/Account'), callback);
};
```
The ```account``` field is not define and an error is issued (```TypeError: Cannot read property 'href' of null```)
The account information is on ```expandedJwt.body.sub```.

**Comment by robertjd** [comment]
This should now be fixed in 0.18.2
