### ISSUE TITLE
configLoader overwriting cache client pointer

### ISSUE THREAD

**Issue by philipatkinson** [stormpath/stormpath-sdk-node#304]
The configLoader within the Client is overwriting a passed reference to an existing cache (e.g. Regis) instance - from quick inspection is looks like it is making a shallow copy of the instance object.

One quick and dirty solution is simply to replace the shallow copy version of the client with the original pointer before it is passed to the DataStore (something that works for me), but is there a more appropriate solution?

If not, I'm happy to create a pull request for the quick fix..

**Comment by robertjd** [comment]
Hello Philip, thanks for the report.  I have a suggested fix here (in the config loading library):

https://github.com/stormpath/stormpath-node-config/issues/12

Is this the same fix you are suggesting?

**Comment by philipatkinson** [comment]
Yes that is pretty much the same thing. My quick fix was to have
effectively same line in the callback to configLoader.load in lib/Client.js:

if (config.cacheOptions && config.cacheOptions.client)
loadedConfig.cacheOptions.client = config.cacheOptions.client;

but that was merely to avoid the hassle of working out exactly which bit of
the config strategy was causing the issue.

Thanks,

Philip

**Comment by robertjd** [comment]
Hello Philip, I've mad a new release of this library, 0.15.1, that contains a fix for this.  Can you upgrade and let me know if it solves the problem for you?  Thanks!

**Comment by philipatkinson** [comment]
Yes, the issue has been resolved in 0.15.1.

Thanks,

Philip

**Comment by typerandom** [comment]
Closing since issue resolved.
