### ISSUE TITLE
Incorrectly throwing an error when request data does not have refresh_token property

### ISSUE THREAD

**Issue by asargento** [stormpath/stormpath-sdk-node#306]
The refresh_token oauth authenticator is not returning the correct error (invalid_request with statusCode 400) when no refresh_token is specified on the request body.
The authenticator should be returning the error that came from Stormpath API and instead is throwing an error that hides this error returned by the Stormpath API.

The verification on line 31, if the refresh_token field is present on request data and the consequent throw on file /lib/oauth/refresh-grant.js, is the incorrect code.
```javascript
  }else if (!data.refresh_token){
    throw new Error('data does not have refresh_token property');
  }
```

**Comment by robertjd** [comment]
Thanks for the report!  We will look at this as soon as possible.  Can you let me know if this error is blocking your development?

**Comment by asargento** [comment]
This error is not blocking my development, because I have a workaround. But is not an elegant solution.
