### ISSUE TITLE
Revoke token obtained via authenticateApiRequest?

### ISSUE THREAD

**Issue by tanzim** [stormpath/stormpath-sdk-node#310]
Is there a way to revoke tokens obtained through authenticateApiRequest[1]? I see that AuthenticationResult is derived from InstanceResource so has a `delete` method, question is, is that enough?

[1] http://docs.stormpath.com/nodejs/api/application#authenticateApiRequest?

**Comment by robertjd** [comment]
Hello @tanzim , these tokens (which are an implementation of the Oauth2 `client_credentials` grant workflow) are created by our SDK and are not retained in a database.  This is different from our [password grant tokens](http://docs.stormpath.com/guides/token-management/), which *are* retained in the Stormpath database and created by invoking our REST API.  Password grant tokens can be deleted by issuing a delete request to our REST API.

If you need to revoke tokens that are created by the SDK for `client_credentials`, you will have to maintain your own blacklist of tokens in your application, and check incoming tokens as part of your authentication process to see if they have been blacklisted (revoked).  Please let me know if I can offer assistance with that implementation.  In the future we may move the client credential workflow to our API, like we have done with the password grant flow.

Having the delete method on an authentication result doesn't make much sense, my apologies for that confusion.

**Comment by tanzim** [comment]
Hi @robertjd 
Ah, that makes some sense. The documentation could do with some improvement indeed. 

WRT OAuthAuthenticator, is validation (via authenticate) a server call or does the SDK cache the information (given the client was initialized with Redis)? I ask because we'd rather avoid another server call on high volume API endpoints.

I'm not too worried with maintaining a blacklist for now as we issue access tokens with short expiry times (which fits into the whole JWT/stateless token principal), thanks for your help though.

**Comment by robertjd** [comment]
The OAuthAuthenticator, in lib/oauth/authenticator, does make a request to the Stormpath API to validate the token, unelss you build the authenticator with the local validation option.  That looks like this:

```
var authenticator = new stormpath.OAuthAuthenticator(application);
authenticator.withLocalValidation();
authenticator.authenticate(/* data */);
```

Using local validation has security trade-offs, which we've discussed in this documentation for our Express library (in our Express library, you can use a high-level configuration option to control the validation strategy):

http://docs.stormpath.com/nodejs/express/latest/authentication.html#token-validation-strategy

The OAuth authenticators aren't currently documented in our Node API documentation, my apologies for that omission.  We are actively re-writing our Node SDK documentation as JSDOC, and we plan to launch that this month - where all the things will be documented :)

**Comment by typerandom** [comment]
Closing issue since it looks like the question has been answered. Reopen if I'm wrong:)
