### ISSUE TITLE
Custom data cache not flushing on updates

### ISSUE THREAD

**Issue by JADurham909** [stormpath/stormpath-sdk-node#312]
I am having a problem with the client caching custom data even after I have updated it.  Basically, I have this structure:

org: {
    prop1: val
}

I am updating it to:

org: {
    prop1: val,
    prop2: val
}

When I curl it after, the correct values are returned.

```curl -X GET --user X \
     -H "Accept: application/json" \
     -H "Content-Type: application/json;charset=UTF-8" \
  "https://api.stormpath.com/v1/accounts/X/customData"```

But the call to get the account using the SDK is returning the older value still without prop 2.

```account.getCustomData(function (err, customData) {```

Is there a way to disable caching on custom data?

**Comment by JADurham909** [comment]
If I remove customData from cacheHandler.js it works of course.

var CACHE_REGIONS = ['applications', 'directories', 'accounts', 'groups',
  'groupMemberships', 'tenants', 'accountStoreMappings','apiKeys','idSiteNonces'];

I assume there is a bug here, is there a way to configure it externally without having to fork?

**Comment by robertjd** [comment]
Thanks for the report!  Can you let us know which method you are using when you are trying to save the custom data?  E.g. `account.save()` or `account.customData.save()`?   

@typerandom can you investigate?  Also see this:

https://github.com/stormpath/express-stormpath/issues/156

It's essentially describing the same problem.

**Comment by JADurham909** [comment]
account.customData.save()

**Comment by JADurham909** [comment]
I have only seen this on objects that are nested and modified so far.

**Comment by JADurham909** [comment]
Here is a code example:
Basically we start with 

{
   org: {
              test1:''
          }
}

and merge in

{
   org: {
              test2:''
          }
}

and expect

{
   org: {
              test1:''
              test2:''
          }
}

```	merge(json, callback) {

		let mergeData;

		if (_.isString(json)) {
			try {
				mergeData = JSON.parse(json);
			} catch (ex) {
				return callback(ex);
			}
		} else {
			mergeData = json;
		}

                //merge new data into customData
                //direct assignment fails as well
                 //deep-merge, lodash, doesnt matter how we do it same result
                 //server is updated correctly, but pulling the data back out it is stale
		m.recursive(account.customData, mergeData);

		account.customData.save(callback);
	}```

**Comment by typerandom** [comment]
I'm looking into this issue now.

**Comment by typerandom** [comment]
Hi again,

I have tried reproducing this, but haven't succeeded. Could you provide me with the configuration you use when you instantiate `stormpath.Client`?

Also, do you see this issue running locally (i.e. when running as one process), or is it only experienced when running in production/in a cluster?

Thanks!

**Comment by JADurham909** [comment]
It is not in cluster.

Here is the project structure:

application
->node_modules
	->stormpath
	->custom module
		->stormpath

I noticed NPM is brining in the module in twice, and that might possibly be related to the cache problems?

I would think it would be ok since its still one process and memory space, but there could be something in code causing an issue.

I have attempted to switch to a Redis backend, but still experience the same issue on the latest version.  ‘

If you are interested in a screen share session I can spend 15 minutes demonstrating the issue.

Thanks!

**Comment by JADurham909** [comment]
```stormpath:
  apiKey:
    id: X
    secret: X
  application:
    href: https://api.stormpath.com/v1/applications/X
  expand:
    customData: true
    groups: true
  cacheOptions:
    store: 'redis'
    connection:
      host: 'X'
      port: 6379
    options:
      return_buffers: false
    ttl: 0
    tti: 0
```

**Comment by typerandom** [comment]
Thank you. I'm trying out your settings now. Also, if you have 15 minutes for a screen share now, then that would be great.

**Comment by JADurham909** [comment]
As it turns out, the issue was mine.  I was decoding the JWT in a middleware and setting the account on a request.  One of my calls was using the custom data off this token rather than fetching the new token.  Sorry about that.

**Comment by typerandom** [comment]
Ok. But great that you found the issue!
