### ISSUE TITLE
Add organization support / organization mapping support for directories

### ISSUE THREAD

**Issue by JADurham909** [stormpath/stormpath-sdk-node#313]
It seems we are allowed to get the directories for an organization, but not the other way around when we have an account -> directory(s) -> organization(s).  This would be helpful in cases where users login via the main domain rather than a tenant sub domain and we do an automatic redirect.

**Comment by robertjd** [comment]
These collections are being added to our REST API this week, I'll update this issue when they are available.

**Comment by robertjd** [comment]
These collections are now available in the REST API, the following methods need to be added to the Directory resrouce:

getOrganizations()

getOrganizationMappings()
