### ISSUE TITLE
Provide a way to specify the Redis key prefix in cacheOptions

### ISSUE THREAD

**Issue by JADurham909** [stormpath/stormpath-sdk-node#317]
It would be really useful to specify a prefix to Redis keys so they look like this:

myapp:http://X

This means in RDM for instance, the keys are organized by the application hosting it.

Currently they just show up as 'http' because of the colon in the url.

<img width="1440" alt="screen shot 2015-12-20 at 9 59 54 am" src="https://cloud.githubusercontent.com/assets/574966/11918465/6ec9f458-a700-11e5-8a44-e9f32272cf46.png">

**Comment by robertjd** [comment]
Hey Justin, this can certainly be done!  Simply pass the option like this:

```javascript
var stormpath = require('stormpath');

var client = new stormpath.Client({
  cacheOptions: {
    store: 'redis',
    options: {
      prefix: 'stormpath-prefix:'
    }
  }
});
```

The `options` object can be used to pass any option that is supported by the `node-redis` library.  For more information about our Redis configuration, please see:

http://docs.stormpath.com/nodejs/api/client#redis

**Comment by JADurham909** [comment]
That did it, thank you!
