### ISSUE TITLE
What's the difference between this module and express-stormpath?

### ISSUE THREAD

**Issue by cleechtech** [stormpath/stormpath-sdk-node#322]
`npm install stormpath` vs `npm install express-stormpath`.. What is the difference? Why are there two repos?

I am using express for my web server so I'm assuming that I should use express-stormpath, pros and cons?

**Comment by robertjd** [comment]
This module, `stormpath`, is a REST client library for the Stormpath API.  It is meant to make it easy to use our REST API, but not do anything that is specific to a particular web framework.

`express-stormpth`, on the other hand, is highly specific to Express.js.  It handles issues like rendering login forms and asserting that users are logged into your application.  Internally it depends on `stormpath` to talk to our REST API, when needed.

If you are using Express for your server, you should definitely use `express-stormpath`.

**Comment by cleechtech** [comment]
Found the answer on [SO](http://stackoverflow.com/questions/32359759/i-want-to-use-stormpath-express-js-and-node-js-do-i-want-stormpath-express-or) also! Thank you
