### ISSUE TITLE
Can't set expiration on JWT

### ISSUE THREAD

**Issue by souptown** [stormpath/stormpath-sdk-node#324]
AuthenticationResult.getAccessTokenResponse() will always return an undefined "expires_in" property, because nJwt does not use a ttl property as stormpath-sdk_node expects. nJwt uses "exp" instead of "ttl".

**Comment by robertjd** [comment]
Hi @souptown , thank you for the report.  It also seems that the `ttl` option that is passed to `authenticateApiRequest` is not used at all, is that the method you are attempting to use?

Until we fix this, I presume you can work around the issue by manually setting the `expires_in`?  Please let me know if this is not doable.  Thanks!

**Comment by souptown** [comment]
Yep - setting ```expires_in``` on the JWT returned from ```getAccessTokenResponse``` works.

```
server.post('/oauth/token', function (req, res, next) { 
    stormpathApplication.authenticateAccount({
            username: req.body.username,
            password: req.body.password
        }, function (err, authenticationResult) {
            if (err) throw err;
            var jwt = authenticationResult.getJwt(),
                tokenResponse;
            if (jwt) {
                tokenResponse = authenticationResult.getAccessTokenResponse(jwt);
                tokenResponse.expires_in = 60 * 30;
                res.json(tokenResponse);
            }
            return next();
        });
});
```

Thanks
