### ISSUE TITLE
Add custom claim to generated JWT?

### ISSUE THREAD

**Issue by tanzim** [stormpath/stormpath-sdk-node#331]
Hi,
I was wondering if there's a mechanism to attach custom claims to the generated JWT via http://docs.stormpath.com/nodejs/api/application#authenticateAccount? 

A great use-case for this is attaching data that could be looked up directly from the token, without poking into the account's custom data (thereby saving network calls and/or database lookups). 

For example, it is often the case that when integrating Stormpath with an existing system, some notion of a user in the existing system (for example a userId) would be used as a surrogate to the account in Stormpath and stored as custom data in the account object. Once identity verification with Stormpath happens, that surrogate key (userId) is then used to refer to resources in the existing system, minimizing integration cost.

Thanks!

**Comment by robertjd** [comment]
Hi @tanzim ,  you can do this by requesting the JWT, modifying it, then requesting a new access token response.  That would look like this:

```
application.authenticateAccount(data, function(err, authenticationResult){
    if(err){
      throw err;
    }

    var jwt = authenticationResult.getJwt();

    jwt.body.custom_claim = 'foo'

    console.log(authenticationResult.getAccessTokenResponse(jwt));
});
```

Hope this helps!
