### ISSUE TITLE
SAML support

### ISSUE THREAD

**Issue by robertjd** [stormpath/stormpath-sdk-node#332]
In order to work with SAML via our REST API, the following needs to be done in this SDK.

* Create a `SamlProvider` class which has the methods `getAttributeStatementMappingRules` and `getServiceProviderMetadata`.  The `Directory.getProvider` method will need to use this new class if the provider resource has a provider ID of `saml`, otherwise it can continue using the generic `Provider` class.

* Create a `SamlIdpUrlBuilder`, which will be exposed as `require(‘stormpath’).SamlIdpUrlBuilder`.  The usage will be `var samlIdpUrlBuilder = new SamlIdpUrlBuilder(application)`.  Then the builder will have the method `samlIdpUrlBuilder.build()`, which will return a string which is the location that the user should be redirected to.  To get this URL , the builder will need to implement [this flow](https://docs.stormpath.com/rest/product-guide/latest/005_auth_n.html#step-1-initiate-the-flow)

* Create the a new authenticator,  `StormpathAssertionAuthenticator` that will implement [this part](https://docs.stormpath.com/rest/product-guide/latest/005_auth_n.html#step-5-stormpath-response-with-jwt) of the flow (validating the incoming JWT response and returning an authentication result, the result should have a `getAccount` method).  This authenticator will be used for handling SAML callbacks as well as ID Site callbacks (we'll deprecate `Application.handleIdSiteResult` in favor of this new authenticator.

**Comment by omgitstom** [comment]
Test
