### ISSUE TITLE
Error initiating client when $HOME is not defined

### ISSUE THREAD

**Issue by JamesSkinner** [stormpath/stormpath-sdk-node#338]
I have just upgraded the version of the Stormpath client we are using from 0.9.0 to 0.15.2 and it has introduced the following error on initialisation of the `Client` object:

```
new stormpath.Client({
        apiKey: new stormpath.ApiKey(
            process.env.STORMPATH_API_KEY_ID,
            process.env.STORMPATH_API_KEY_SECRET
        )
});

TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at exports.join (path.js:358:36)
    at expandHomeDir (/myapp/node_modules/stormpath/node_modules/stormpath-config/node_modules/expand-home-dir/index.js:11:10)
    at new LoadAPIKeyConfigStrategy (/myapp/node_modules/stormpath/node_modules/stormpath-config/lib/strategy/LoadAPIKeyConfigStrategy.js:14:19)
    at module.exports (/myapp/node_modules/stormpath/lib/configLoader.js:17:5)
    at new Client (/myapp/node_modules/stormpath/lib/Client.js:43:45)
```

This looks to be caused by the fact that the `HOME` environment variable is not defined in our production environment (AWS Opsworks). I have resolved this for now by just setting it in code before creating the `Client` but I think this library should handle the situation where this environment variable does not exist (although you could argue that actually it is the expand-home-dir module which does not handle it correctly).

**Comment by typerandom** [comment]
Thank you for reporting this issue!

The SDK should definitely be able to handle the scenario where the home variable isn't being set. So I'm filing this as a bug.

Since `expand-home-dir` was last updated 2 years ago, I think the solution will be to move from using the that module ([it's very little code](https://github.com/azer/expand-home-dir/blob/master/index.js)), and instead have that code inline in the project.

**Comment by typerandom** [comment]
@JamesSkinner This is now fixed in our v0.15.3 release. Let me know how that works for you :)

Cheers!

**Comment by JamesSkinner** [comment]
@typerandom Thanks, have tested this though and am getting a different error:

```
Fatal Error:  Error: Unable to load '/mayapp/node_modules/stormpath/lib/config.yml'. Environment home not set.
    at LoadFileConfigStrategy.process (/myapp/stormpath/node_modules/stormpath-config/lib/strategy/LoadFileConfigStrategy.js:29:23)
```

Cheers

**Comment by typerandom** [comment]
@JamesSkinner That is strange. Are you able to share the configuration that you're using? (i.e. with sensitive values omitted)

**Comment by typerandom** [comment]
@JamesSkinner Sorry, my mistake. I found the error and will have a release for you in a little moment.

**Comment by typerandom** [comment]
@JamesSkinner Sorry about that. I now have a new release, v0.15.4 that should work for you. Could you please try this and let me know how that works for you :)

**Comment by JamesSkinner** [comment]
@typerandom Thank you! Working fine now.

**Comment by typerandom** [comment]
Awesome :) Closing this issue now.
