### ISSUE TITLE
Error when using baseUrl

### ISSUE THREAD

**Issue by grigorievs** [stormpath/stormpath-sdk-node#386]
When passing the baseUrl parameter for the Client it gives an error.
i.e. client = new stormpath.Client({apiKey: apiKey, baseUrl: 'https://api.stormpath.com/v1'});

Error: 
Error: Unable to execute http request GET /tenants/current: options.uri must be a path when using options.baseUrl

**Comment by robertjd** [comment]
This is fixed in the latest version, 0.17.3
