### ISSUE TITLE
package.json references a devDependancy that no longer exists

### ISSUE THREAD

**Issue by stuartking** [stormpath/stormpath-sdk-node#421]
It looks like the devDependancy `expand-home-dir` had a new version published yesterday (0.0.3) and in the process, the publisher decided to remove the older 0.0.2 version (!?!?). 

Since package.json references the exact version for this lib, then npm install fails if either `--dev` is used, or another project references 'stormpath' as a dependancy in it's package.json:

```
$ npm install stormpath --dev
npm ERR! Darwin 15.2.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "stormpath" "--dev"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! version not found: expand-home-dir@0.0.2
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sking/tmp/npm-debug.log
```

**Comment by robertjd** [comment]
Oh blarg, how annoying!  I've re-opened this PR on our repo as #422 (so tests can run), thanks @stuartking for the quick action on this one!
