### ISSUE TITLE
Error: version not found: expand-home-dir

### ISSUE THREAD

**Issue by RobertBaron** [stormpath/stormpath-sdk-node#432]
npm install stormpath@0.13.2
npm WARN package.json express-jsend@0.1.0 No repository field.
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"1.4.28"})
npm ERR! Error: version not found: expand-home-dir@0.0.2
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-named.js:125:12
npm ERR!     at saved (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-504.16.2.el6.x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "stormpath@0.13.2"
npm ERR! cwd /home/websites/zamunda/dist
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! not ok code 0

**Comment by typerandom** [comment]
This issue should be fixed. I'm closing it.
