### ISSUE TITLE
Redis Sentinel Support

### ISSUE THREAD

**Issue by blyork** [stormpath/stormpath-sdk-node#467]
It appears that the current implementation of the [RedisStore](https://github.com/stormpath/stormpath-sdk-node/blob/master/lib/cache/RedisStore.js) uses the ["redis"](https://www.npmjs.com/package/redis) module. After doing some research it appears that this module does not currently support the use of Redis Sentinels. Is there any plans on creating an alternative redis store that allows for sentinels? It looks like ["ioredis"](https://www.npmjs.com/package/ioredis) supports them.

**Comment by robertjd** [comment]
Thanks for the question!  The API for ioredis appears to be the same as redis, as such it appears that you can just pass an instance of ioredis to our client constructor:

```
var Redis = require('ioredis');
var stormpath = require('stormpath');

var redis = new Redis();

var client = new stormpath.Client({
  cacheOptions: {
    store: 'redis',
    client: redis
  }
});
```

Can you give this a try and let me know if it works for you as well?  Thanks!

**Comment by blyork** [comment]
I am getting the below error:

```
[ioredis] Unhandled error event: Error: connect ETIMEDOUT
    at Socket.<anonymous> (/home/sensorfact/app/node_modules/ioredis/lib/redis.js:287:21)
    at Socket.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at Socket.emit (events.js:179:7)
    at Socket._onTimeout (net.js:332:8)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

This is my redis config:

```json
    "redis": {
        "sentinels": [{
            "port": 26379,
            "host": "redis-sentinel"
        }],
        "name": "sensorfact",
        "password": "theSuperSecretPassword"
    }
```

This is my setup:

```javascript
            // Load Stormpath.
            const stormpathOptions = {
                apiKey: new stormpath.ApiKey(config.stormpath.apiKey.id, config.stormpath.apiKey.secret)
            };

            if (config.redis) {
                stormpathOptions.cacheOptions = {
                    store: 'redis',
                    client: new Redis(config.redis)
                };
            }

            const spClient = new stormpath.Client(stormpathOptions);
```

**Comment by robertjd** [comment]
Thanks, do you have more context for the error?  On the surface it looks like the ioredis client had trouble communicating with the redis server, which would be outside the scope of this library.

**Comment by blyork** [comment]
I am running everything in a Kubernetes environment using the official redis and nodejs docker images. I have a Kubernetes service that is pointing the the Kubernetes pods that are running the Redis Sentinels. The IP to this service and be resolved using 'redis-sentinel' as can be seen below:
```shell
redis-cli -h redis-sentinel -p 26379 -a 'theSuperSecretPassword' --csv SENTINEL get-master-addr-by-name sensorfact
"10.27.252.131","6379"
```
This command was run from another pod in the same environment.

**Comment by blyork** [comment]
Update. This might be a Redis Sentinel election issue.

**Comment by blyork** [comment]
I forgot to mention this earlier but your recommended fix worked. Thanks.
