### ISSUE TITLE
Fix documentation for quickstart

### ISSUE THREAD

**Issue by edjiang** [stormpath/stormpath-sdk-node#477]
We don't need to create an explicit stormpath.ApiKey object, because we it checks search baths by default. So we should take that out of the quickstart.  I was misled :(

Makes my code easier; for instance: 

https://github.com/SimplicityMobile/Implicity/commit/3206608dc125f0720c720dd70957d20d2841d6f7

**Comment by robertjd** [comment]
This is resolved in the new documentation: http://docs.stormpath.com/nodejs/jsdoc/Client.html

Please follow up if it's still unclear.
