### ISSUE TITLE
Change user password for user that is logged in.

### ISSUE THREAD

**Issue by EricMentele** [stormpath/stormpath-sdk-node#479]
Can you change the user's password if they are logged in? I have an iOS app that has a change password button under account settings. I want a user to be able to type in a new password there and update their Stormpath account.

**Comment by robertjd** [comment]
This library doesn't manage login sessions (that is what express-stormpath does), this library allows you to work with the account objects at a low level, so if you have an account object, from a method like application.getAccount(), then you can do this:

```
account.pasword = 'new password';
account.save()
```

Hope this helps!

**Comment by EricMentele** [comment]
Thank you! Got it working.
