### ISSUE TITLE
getUser does not respect web.accessTokenCookie.name and web.refreshTokenCookie.name.

### ISSUE THREAD

**Issue by blyork** [stormpath/stormpath-sdk-node#482]
getUser is using cookies.access_token and cookies.refresh_token instead of cookie[config.web.accessTokenCookie.name] and cookie[config.web.refreshTokenCookie.name].

**Comment by robertjd** [comment]
This is an issue for the stormpath/express-stormpath library and was resolved in stormpath/express-stormpath#422, which will go out in the next release. I'm planning to make a release this week.
