### ISSUE TITLE
Unable to authenticateAccount immediately following createAccount

### ISSUE THREAD

**Issue by r3wt** [stormpath/stormpath-sdk-node#491]
our app relies on both signup/login to return a jwt, which we obtain from `authResult.getAccessToken()`. What we are finding is that when we call `authenticateAccount()` from `createAccount()`'s callback, we get the "invalid username or password" response, however when we check the accounts in our stormpath accounts list its there. This leads me to believe that this is some type of race condition. 

I can think of 3 possible solutions:

1. stormpath should not respond to create account until the resource is created on your end, ensuring a call to `authenticateAccount` will not fail due to this race condition.

2. we can use a `setInterval` loop to try to auth until the resource is created on your end. this seems like a bad idea to me. we can probably do unique timeouts with es6's `Symbol`'s but still, i don't like it, as we open ourself up to some memory leaks and would need to track all open timeouts, and periodically flush them.

3. stormpath should provide a `getAccessToken()` method on the `createdAccount` object returned in the callback of `createAccount`.

Would appreciate any comments/help on this matter, this is a fairly serious issue.

**Comment by robertjd** [comment]
Hello @r3wt , thanks for the information!  A few questions:

* Is the account's status "UNVERIFIED"?  This would cause the error.

* Which version of this library are you using?  We recently fixed a related issue with caching (#483) and this is available in the latest v0.18.3

**Comment by r3wt** [comment]
@robertjd 

 * i don't know. if possible, can i pass a flag in createAccount to always verify the account. it has no effect on our security model either way.

 * `"stormpath": "^0.18.3"` is shown in package.json so i assume we are using latest version.

**Comment by r3wt** [comment]
@robertjd `after investigating, the status of the user is `enabled`. so that is not the issue. race condition on your end. i tried working around with setTimeout but it consistently returns "invalid username or password" until the max tries is exceeded.

**Comment by robertjd** [comment]
Thanks @r3wt .  Can you drop a note about any caching configurations you are using?  I have to hand this off to someone else on the team because I'm about to leave for holiday.

**Comment by typerandom** [comment]
@r3wt I'm unable to reproduce this. Could you provide code on how to reproduce it?

I.e. if you try the code that I used, then at least with my configuration/application, I'm unable to reproduce the issue. Would be interesting to see if you still see the error there:

https://gist.github.com/typerandom/8c55b829cae9d0045de25524bd449867

**Comment by r3wt** [comment]
@typerandom 

here is our implementation:

in **app.js**
```js
var stormpath = require('stormpath');

global.spClient = spClient = new stormpath.Client({
    apiKey: new stormpath.ApiKey(
        config.stormpath.apikey,
        config.stormpath.secret
    )
});
```

in **controllers/User.js** method `signup(req,res)`
```js
signup: function (req, res) {

	if (!req.body.email || !req.body.password ) {
		return res.error('Missing email or password');
	}

	spClient.getApplication(config.stormpath.address, function (err, app) {
	
		if (err) {
			return res.error(err);
		}

		app.createAccount({
			givenName: req.body.name,
			surname: req.body.last.name,
			email: req.body.email,
			password: req.body.password
		}, function (err, createdAccount) {
		
			if (err) {
				log.error(err);
				return res.error(err.userMessage);
			}
			

			app.authenticateAccount({email: req.body.email,password: req.body.password }, function (err,authResult) {
				
				if(err){
					return res.error(err.userMessage);
				}
				
				var user = new model.User({
					email: createdAccount.email,
					firstName: createdAccount.givenName,
					lastName: createdAccount.surname,
					fullName: createdAccount.givenName + ' ' + createdAccount.surname,
					accountActive: true,
					profileComplete: false
				});
				
				
				user.save(function userCreated(err, newUser) {

					if (err) {
						log.error(err);
						
						//delete the created account since we failed to insert locally.
						authResult.getAccount(function(err2, account) {
							account.delete(function(){
								return res.negotiate(err);
							});
						});
						return res.error(err);//send error and prevent further execution.
					}
					//log user in

					var spt = authResult.getAccessToken(); //stormpathtoken
					var uid = newUser.id instanceof ObjectId ? newUser.id.toString() : newUser.id;
					
					log.debug('stormpath token: %s user id: %s',spt,uid);
					
					redis.set(spt,uid);//set value in db for jwt challenge lookup

					req.user = {
						id: newUser.id,
						email: newUser.email,
						isAdmin: !!newUser.admin,
						date: (new Date()).toISOString(),
						__spt: spt
					};
					
					//todo add stormpath token(s) into req.user
					var jwt = require('jsonwebtoken');
					jwt.sign(req.user, config.jwt.secret , {
						expiresIn: '365 days',
					}, function (err, token) {

						if (err !== null) {
							//todo handle the error
							return res.error(err);
						}
						//finally, send the response
						res.apiResponse({
							id: newUser.id,
							email: newUser.email,
							isAdmin: !!newUser.admin,
							token: token,
						});

					});

				});
			});
		});
	});
},
```
here is our implementation in full. i'm not sure why it fails. could it be that we should instead construct the sp client every request?

**Comment by typerandom** [comment]
@r3wt From looking at your code, I'm not able to see why it should fail either. And creating new instances of the Stormpath Client on every request shouldn't make any difference.

What happens if you run the code for the application that I created:
https://gist.github.com/typerandom/8c55b829cae9d0045de25524bd449867

Are you able to see the same issue there? Since I'm unable to reproduce it on my end what I'd want to do is isolate the problem as much as possible, to see if it's local to your tenant/application or the Node SDK.

**Comment by r3wt** [comment]
@typerandom i got it. i was passing `{email: fields.email,password: fields.password}` which makes logical sense. your api expects `{username: fields.email,password: fields.password}` which makes no logical sense.

**Comment by typerandom** [comment]
Well noticed. I think it's logical to pass username/password when doing username/password authentication. The thing that is confusing in your example is that when you provide only email and not a username, what happens in the background is that the username (when unspecified) automatically defaults to the email. I'm sorry for the inconvenience, but happy that you were able to solve the issue.
