### ISSUE TITLE
no method for creating Organizations?

### ISSUE THREAD

**Issue by r3wt** [stormpath/stormpath-sdk-node#509]
https://docs.stormpath.com/rest/product-guide/latest/multitenancy.html#how-to-create-an-organization

but in the sdk documentation, there is no such method.

**Comment by robertjd** [comment]
Hi @r3wt , sorry about that!  I'm re-writing our API docs (literally right now) in JsDoc, our current ones are missing a few methods in the meantime :(  Standby for fancy new JsDocs, coming in the next week!

You can use `client. createOrganization(organization, callback)` to create organizations.  Please let me know if you have any issues.

Best,
Robert

**Comment by r3wt** [comment]
I am new to this, and the lack of documentation is making it difficult to understand. its not just you guys, we are evaluating several providers and they all assume the reader already understands the subject matter.

I basically need to create Organizations to facilitate multi tenancy. we have stormpath working already, just figuring out how to create Organizations for our tenants, and then store users in each organization, but there is not much documentation on the subject other than a few brief paragraphs in the marketing pages.

**Comment by r3wt** [comment]
quick question, how can i specify the organization in `application.createAccount()`. 

our use case is pretty simple:

1. we are an api. 
2. our tenants are 3rd party apps, that pass JWTs with a payload of `{ tenant: 'tenantid' }` to endpoints to identify which tenant the request is coming from. the tenant is equal to the `nameKey` of the `Organization`.
3. our `spClient` is configured as a global variable, exposed as `global.spClient`. instead of reconfiguring the client for each tenant (which would cause obvious problems), we wish to set the account store at insertion time by configuring `accountStore` as an option to `application.createAccount`. why is this use case not supported, and if it is it is poorly documented

**Comment by mdeggies** [comment]
Hey Garret -- I know we spoke briefly about this in support, but I wanted to reply here too. We're currently working on a new Node API reference that will describe all of the methods available. That will be released within the next week or two. 

To answer your specific question- Organizations do not hold accounts. You'll need to map Groups or Directories as Account Stores to your Organizations, and then add Accounts to those Groups/Directories. This is explained in-depth in our multi-tenancy guide here: https://docs.stormpath.com/rest/product-guide/latest/multitenancy.html#multi-tenancy-and-the-stormpath-data-model

Let me know if you have any questions about that.

**Comment by r3wt** [comment]
ok, so from your post i am taking away that i should:

1. create organization.
2. create directory for organization.
3. create accountStoreMapping for organization. 

It shouldn't be this difficult, you should have abstracted for this common use case. in my opinion, your practices are hostile to adoption.

look at this:

```js

	signup: function(req,res){
		
		//needed for tenant reg at stormpath
		var name = req.body.name || false;
		var email = req.body.email || false;
		var pass  = req.body.password || false;
		
		var tenantCreationFields = {
			email: email,
			password: pass,
		};
		
		
		//needed for customer reg at stripe
		var required = {
			'card_number':'number',
			'expiration_month':'exp_month',
			'expiration_year':'exp_year',
			'card_security_code':'cvc'
		};
		
		var tokenFields = {
			card: {
				number: null,
				exp_month: null,
				exp_year: null,
				cvc: null
			}
		};
		
		for(var prop in required){
			
			if(!req.body.hasOwnProperty(prop)){
				return res.error('missing required parameter `'+prop+'`');
			}
			
			//unpack prop of required as prop in tokenFields.card
			tokenFields.card[required[prop]] = req.body[prop]; // wtf
			
		}
		
		//now we should be ready to create the token.
		stripe.tokens.create(tokenFields, function(err, token) {

			var error = stripeError(err);

			if(error){
				return res.error(error);
			}
			
			var m = model.Tenant;
		
			var tenant = new m({
				name: name,
				pubkey: uniqid.v1(),
				privkey: uniqid.v4(),
			});
			
			tenant.save(function(err,result){
				//create the tenant membership
				stripe.customers.create({
					description: 'Customer for Tenant id# '+ result._id,
					source: token,
					plan:'tenant-membership' //NOTE: the plan with this id must be created in both TEST and LIVE environments at stripe or it fails.
				}, function(err, customer) {
					
					spClient.getApplication(config.stormpath.address, function (err, app) {
						
						spClient.createDirectory({
							name: result._id,
							description: 'account store for Tenant id# '+ result._id
						},function(err,dir){
							app.createAccount(tenantCreationFields,{ accountStore: { nameKey: 'tenants' } },function(err,account){
							
								model.Tenant.update({ _id: result._id },{stripe_id: customer.id, stormpath_id: account.id },{},function(err,nAffected){
								
									app.createOrganization({
										name: 'Organization for Tenant id# '+result._id,
										nameKey: result._id,
										status: 'ENABLED'
									},function(err,org){
										
										org.createAccountStoreMapping(dir,function(err,createdAccountStoreMapping){
											app.authenticateAccount({
												username: tenantCreationFields.email,
												password: tenantCreationFields.password,
												accountStore: { nameKey: 'tenants' }
											},function(err,authResult){
												
												//we are already using req.user and req.tenant
												//express-jwt already uses auth header for req.user.
												//how to store tenant sessions?
												
												//for now patch these sessions in as req.user.tenantSession
												if(!req.hasOwnProperty('user')){
													req.user = {};
												}
												
												req.user.tenantSession = {
													id: result._id,
													name: result.name,
													email: account.email
												};
												
												jwt.sign(req.user, config.jwt.secret , {
													expiresIn: '365 days',
												}, function (err2, token) {
													if (err) {
														return res.error(err);
													}
													res.apiResponse({
														id: result._id,
														email: account.email
														token: token,
													});
												});
											});	
										})
									});
								});
							});							
						});
					});
				});
			});
		});
	},
```

do you feel comfortable about this? i sure don't.

**Comment by r3wt** [comment]
also, you still didn't answer my question at all @mdeggies

**Comment by mdeggies** [comment]
Garret, sorry that isn't clear from our docs -- as I mentioned earlier, we're working on a brand new version that will be out soon and will explain all of the methods available in Node. Our Node SDK is pretty low level, but we do have an Express integration you can check out that we will be adding multi-tenancy support to very soon. Our integrations are much easier to work with if you don't want to be concerned with low level details.

**Comment by mdeggies** [comment]
The flow should be like this:

1. Create an organization
2. Create a Directory or Group
3. Map that Directory/Group to your Organization
4. Given the Organization name key, create an Account that will be stored in the default Directory/Group -- if you've created social Directories, your social Accounts will magically be placed in the right ones 

Below is a simple example:

```
var stormpath = require('stormpath');
var client = new stormpath.Client();

client.getOrganizations({nameKey:'your-name-key'},function(err, organizationCollection) {
  var foundOrg = organizationCollection.items[0];

  var newAccount = {
    email: 'foo@example.com',
    givenName: 'foo',
    surname: 'bar',
    password: 'Password!A1'
  };

  foundOrg.createAccount(newAccount, function(err, createdAccount){
    console.log(err,createdAccount);
  });
});
```

**Comment by r3wt** [comment]
thanks @mdeggies. in regards to the higher level library, its a bit to specific in its use case, and doesn't support many things we need do to. a library that extracts away implementation details of your api seems like it would be a no brainer, but i digress. we will use the information you have provided to make it work.

**Comment by mdeggies** [comment]
You're very welcome, @r3wt :) 
I will be sure to pass your notes along to our JS Engineers.

**Comment by r3wt** [comment]
i've tried all given steps and get this response:

```
{"status":500,"data":{"name":"ResourceError","status":400,"code":5114,"userMessage":"The specified Account Store is not one of the Application's assigned Account Stores.","developerMessage":"The specified Account Store is not one of the Application's assigned Account Stores.","moreInfo":"https://docs.stormpath.com/rest/product-guide/latest/errors.html#error-5114","message":"HTTP 400, Stormpath 5114 (https://docs.stormpath.com/rest/product-guide/latest/errors.html#error-5114): The specified Account Store is not one of the Application's assigned Account Stores."},"message":"an error occurred"}```

here' is our controller method thats creating this dummy tenant for testing purposes:

```js
createTestingTenant: function(req,res){
	
	//needed for tenant reg at stormpath
	var tenantCreationFields = {
		email: 'test@test.com',
		password: 'abc123go',
	};
		
	var m = model.Tenant;

	var tenant = new m({
		name: 'Tenant Test',
		pubkey: uniqid.v1(),
		privkey: uniqid.v4(),
	});
		
	tenant.save(function(err,result){

		spClient.createDirectory({
			name: result._id,
			description: 'account store for Tenant id# '+ result._id
		},function(err,dir){
			
			//get tenant org
			spClient.getOrganizations({nameKey:'tenants'},function(err, organizationCollection) {
				var foundOrg = organizationCollection.items[0];
				foundOrg.createAccount(tenantCreationFields,function(err,account){
					spClient.getApplication(config.stormpath.address, function (err, spApp) {
						spClient.createOrganization({
							name: 'Organization for Tenant id# '+result._id,
							nameKey: result._id,
							status: 'ENABLED'
						},function(err,org){
							
							org.createAccountStoreMapping(dir,function(err,createdAccountStoreMapping){
								spApp.authenticateAccount({
									username: tenantCreationFields.email,
									password: tenantCreationFields.password,
									accountStore: { nameKey: 'tenants' }
								},function(err,authResult){
									
									if(!err){
										return res.apiResponse('tenant created');
									}else{
										return res.error(err);
									}
									
								});	
							})
						});
					});
				});
			});
		});
	});
}
```

i am wondering what i have done wrong here?

**Comment by r3wt** [comment]
@mdeggies after following all instructions, it is not possible to now authenticate as there is no authenticateAccount method for directory/organization, atleast its not documented if it does exist

**Comment by r3wt** [comment]
```
//creates the public tenant for testing purposes
createPublicTenant: function(req,res){
	
	//needed for tenant reg at stormpath
	var tenantCreationFields = {
		email: 'test@test.com',
		password: 'Tenant01',
	};
		
	var m = model.Tenant;

	var tenant = new m({
		name: 'Public Tenant',
		pubkey: uniqid.v1(),
		privkey: uniqid.v4(),
		is_free: true,
	});
		
	tenant.save(function(err,result){

		spClient.createDirectory({
			name: result._id,
			description: 'account store for Tenant id# '+ result._id
		},function(err,dir){
			
			//get tenant org
			spClient.getOrganizations({nameKey:'tenants'},function(err, organizationCollection) {
				
				var foundOrg = organizationCollection.items[0];
				
				foundOrg.createAccount({ email: tenantCreationFields.email, password: tenantCreationFields.password, givenName:'Public',surname:'Tenant' },function(err,account){
					if(err){
						return res.error(err);
					}
					spClient.getApplication(config.stormpath.address, function (err, spApp) {
						
						if(err){
							return res.error(err);
						}
						
						spClient.createOrganization({
							name: 'Organization for Tenant id# '+result._id,
							nameKey: result._id,
							status: 'ENABLED'
						},function(err,org){
							
							org.createAccountStoreMapping({
								accountStore: {
									href: dir.href
								},
								isDefaultAccountStore: true,
								isDefaultGroupStore: true
							},function(err,createdAccountStoreMapping){
								
								if(err){
									return res.error(err);
								}
								
								spApp.authenticateAccount({
									username: tenantCreationFields.email,
									password: tenantCreationFields.password,
									accountStore: { nameKey: 'tenants' }
								},function(err,authResult){
									
									if(!err){
										return res.apiResponse('public tenant created');
									}else{
										return res.error(err);
									}
									
								});	
							})
						});
					});
				});
			});
		});
	});
}
```
@mdeggies how should i authenticate against a directory/organization? the only documented method for authentication is `application.authenticateAccount`, which would require the account store be mapped to the application as well, seemingly for no practical benefit (other than laziness). our code is setup to manage name keys of tenants and use them to select proper account store at login. how should we authenticate for organization/directory. this is not current documented :( @robertjd

**Comment by robertjd** [comment]
All authentication attempts happen against a Stormpath Application, so the Organization (which represents the tenant) must be mapped to Application.

You're code looks correct, as you are passing the Organization name key when calling `application.authenticateAccount()`, which identifies the account store that the account should be in.  Mapping the Organization to the application should be all you need to do.

It may seem un-necessary, but the layering of account stores is actually quite powerful and has been designed to support wide range of multi-tenant use cases.

Best,
Robert

**Comment by r3wt** [comment]
yes, as you can see in the code above, i am trying to authenticate the created tenant within the tenant organization, for which the nameKey is `tenants`. when you say "mapping the organization to the application should be all you need to do", what do you mean? i see no method related to that. i also tried again mapping to both organization and application, result is same. unable to authenticate

**Comment by r3wt** [comment]
oh i see. the tenants org is not mapped to applicaton.

**Comment by r3wt** [comment]
@robertjd so you say my code looks correct, say that your method is powerful, but again offer no explanation why it doesn't work? i went back and made sure that our tenants organization was mapped to the application. i also made sure that when we create the new organization, it is also mapped to the application. still the result is the same, it says authentication failed because the account store is not mapped to the application.

**Comment by mdeggies** [comment]
@r3wt - I'll need a few minutes, but will reproduce and get back to you shortly.

**Comment by r3wt** [comment]
![img](http://puu.sh/qma8T/aaab94f437.png) as you can see, our tenant store is mapped, and as a result of this operation so is the created tenants directory

**Comment by r3wt** [comment]
@robertjd @mdeggies if possible we could take this conversation off of github. possibly onto slack or somewhere more private we can talk that isn't public, so we can communicate more effectively and openly with respect to our employers.

**Comment by r3wt** [comment]
i'm curious, since i created the mapping to the tenant org on the website, could it be that the sdk is not aware of this mapping, though it exists?

**Comment by mdeggies** [comment]
@r3wt: You can join our Stormpath Slack channel at TalkStormpath.slack.com. You can PM me there- I'm mdegges. 

In case this is useful for anyone else, I'll post my reply here too: 

You have to map a Directory or Group as an Account Store to your Organization, **and** map your Organization as an Account Store to your Application. If you've done both of these steps, this code will work:

```
client.getApplication(applicationHref, function (err, application) {
  if(err) {
    console.log(err);
  }

  client.getOrganizations({nameKey:'org1'},function(err, organizationCollection) {
    if(err) {
      console.log(err);
    }

    var foundOrg = organizationCollection.items[0];
    // console.log('foundOrg:',foundOrg);

    var newAccount = {
      email: 'foo@example.com',
      givenName: 'foo',
      surname: 'bar',
      password: 'Password!A1'
    };

    foundOrg.createAccount(newAccount, function(err, createdAccount){
      if(err) {
        console.log(err);
      }

      console.log('createdAccount:',createdAccount);

      var authcRequest = {
        username: createdAccount.email
        password: 'Password!A1',
        accountStore: { nameKey: 'org1' }
      };

      application.authenticateAccount(authcRequest, function(err, result) {
        if(err) {
          console.log(err);
        }

        result.getAccount(function(err, account) {
          console.log(account);
        });
      });
    });
  });
});

```

**Comment by r3wt** [comment]
@mdeggies i will join up there and ping you. fwiw, i have done both of these steps. i can show you are real code there
