### ISSUE TITLE
createIdSiteUrl Organization Field

### ISSUE THREAD

**Issue by mdeggies** [stormpath/stormpath-sdk-node#519]
Am I trippin? Trying to get the organization name field to show up on ID Site via [createIdSiteUrl](http://docs.stormpath.com/nodejs/jsdoc/Application.html): 

```
  var client = req.app.get('stormpathClient');
  client.getApplication('https://api.stormpath.com/v1/applications/$APP_ID', function(err, application) {
    var url = application.createIdSiteUrl({
      showOrganizationField: 'true', //also tried true (without quotes) 
      callbackUri: 'http://localhost:3000/idSiteResult'
    });
    res.redirect(url);
  });
```

I'm redirected properly to https://tenant-name.id.stormpath.io/#/register, but I don't see any new field on this page or the login page.

**Comment by robertjd** [comment]
Hey @mdeggies , the docs were incorrectly saying it should be String, but it should be a Boolean.  I just fixed that.

Can you also confirm that you have some organizations mapped to the application?  This option has no affect if there are no mapped organizations.  Thanks!

**Comment by robertjd** [comment]
Docs were updated, closing - please reopen if there is still a problem with usage.
