### ISSUE TITLE
ApiKey should have getter methods

### ISSUE THREAD

**Issue by mdeggies** [stormpath/stormpath-sdk-node#533]
The ApiKey resource should have convenience methods defined (such as a getter for the account).

https://github.com/stormpath/stormpath-sdk-node/blob/master/lib/resource/ApiKey.js
https://github.com/stormpath/stormpath-sdk-node/blob/master/lib/resource/ApiKey.js

**Comment by typerandom** [comment]
Closing this since it was resolved by #540.
