### ISSUE TITLE
Uncaught Error in JwtAuthenticator

### ISSUE THREAD

**Issue by hellersson** [stormpath/stormpath-sdk-node#549]
I use the following function to authenticate requests with jwts. The jwts are generated by the SDK. It works as expected in my development environment

```
const Stormpath = require('stormpath');
const StormpathApp = options.stormpath;
const Auth = new Stormpath.OAuthAuthenticator(StormpathApp).withLocalValidation();

Auth.authenticate(request.raw.req, (err, authenticationResult) => {

    if (err) {
        return reply(err);
    }

    const credentials = {
        account: authenticationResult.account.href,
        username: authenticationResult.account.username,
        scope: authenticationResult.grantedScopes
    };

    return reply.continue({'credentials': credentials});
});

```

However, in production (Heroku) the callback function of `Auth.authenticate()` is never called and I get the following error:

```
TypeError: Uncaught error: authenticator.authenticate is not a function
 at /app/node_modules/stormpath/lib/jwt/jwt-authenticator.js:131:25
 at /app/node_modules/njwt/index.js:62:7
 at _combinedTickCallback (internal/process/next_tick.js:67:7)
 at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

As far as I know there is nothing wrong with the jwts themselves or the `njwt` parse function. Interestingly, when I switch the jwt with a token generated by another Stormpath App, the JwtAuthenticator correctly returns a JwtParseError ('Signature verification failed');

I'm using version 0.18.5, node version 6.2.2

**Comment by robertjd** [comment]
Hello @hellersson , thanks for the report! A few questions:

* Are you working with a `client_credentials` workflow?
* Can you show me how you're creating the access token?
* How it's coming on on the request?  

I think what's happening is that one of these rules is being violated:

https://github.com/stormpath/stormpath-sdk-node/blob/master/lib/authc/OauthAccessTokenAuthenticator.js#L22-L37

That `validateJwt` function is called by the `OauthAccessTokenAuthenticator` and if there is an error it is returned by the constructor, and not handled in this location:

https://github.com/stormpath/stormpath-sdk-node/blob/master/lib/jwt/jwt-authenticator.js#L130

Which is pretty lame, we should fix that because it makes this problem impossible to diagnose.  But in the meantime can you look at your tokens to see if they violate in of the checks in `validateJwt` ?  Thanks!

**Comment by hellersson** [comment]
Hi @robertjd,

Like you suggested, the problem was a violation of the `validateJwt` checks. Good job!

I was just a just a simple bug: the expiration date of the jwt was not set due to a missing value. 

If you have time to work on that in the future: A more meaningful error message would probably be useful. 

Just for the sake of completeness, I am using the password grant workflow in this case. I create a token using the `getJwt()` function of the `authenticationResult`, in order to add a custom scope to the jwt body.

Thanks for your quick response!

**Comment by robertjd** [comment]
Thanks for the follow up!  You've actually run into the bigger problem: the `authenticationResult.getJwt()` method does an on-demand JWT creation, locally in your server.  Our service doesn't retain the JWT in this case, as such it is missing a `kid` field in the token, which then ends you up in the case where this SDK tried to validate it as if it's a `client_credentials` token.

Have you looked at using the `OAuthPasswordGrantRequestAuthenticator`?  That is the new authenticator to use for the password grant flow, it makes the flow much simpler and our service will retain the token for you:

https://docs.stormpath.com/nodejs/jsdoc/OAuthPasswordGrantRequestAuthenticator.html

My apologies for the mess around this feature.  Our Node SDK was our first offering of OAuth features, and a lot of it was done without the help of the backend API.  We've recently moved all of this functionality to our REST API, and we're refactoring this library accordingly.  The next minor versions will have most of these fixes.  The `authenticationResult.getJwt()` method will go away in our next major version.

**Comment by hellersson** [comment]
That's great! Good to know you keep on working on the SDK. The `OAuthPasswortGrantRequestAuthenticator`sounds promising.

One question: Until now, I have been setting a custom scope on the locally generated jwt for authorization purposes (roles, permissions, etc.). Can I still do that with the new `OAuthPasswordGrantRequestAuthenticator`? I imagine that if I change the token body and sign it with `njwt.compact()` it changes the signature of the accessToken.  

For performance reasons we resorted to the `withLocalValidation` option of `OAuthAuthenticator` when authenticating requests with the jwts generated by the password grant flow. 

I am not sure if I fully understand the concept behind this, but is feasible to do the following?
- generate access_token/refresh_token pairs with the `OAuthPasswordGrantRequestAuthenticator` (with a short `ttl`)
- modify the access_token by customizing the `body.scope`
- authenticating requests with the modified access_token using the `OAuthAuthenticator` (localValidation)
- once the modified access_token is expired, issue a new one by checking the unmodified refresh_token

Since the issue is closed: I'm also available on the Stormpath Slack channel (@dheller)

**Comment by robertjd** [comment]
Hey @hellersson - sorry I missed you on slack, I think we've chatted there before?

To answer your question: yes, you can add scope to the claims body and re-sign the token as you've proposed.  We're actually going to add this to the SDK as a feature (basically re-implementing the "Scope factory" that is stuck on our strange `application.authenticateApiRequest()` method).

The signature of the token will change, but as long as you sign it with the same API Key secret that was used to authenticate the request to our API, when you created the token via the applications `/oauth/token` endpoint (which `OAuthPasswordGrantRequestAuthenticator` is doing for you), then it will all work as expected.
