### ISSUE TITLE
Twitter Social Directory CRUD

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-node#577]
https://stormpath.atlassian.net/wiki/display/AM/Social+Login+V2

**Comment by robertjd** [comment]
This should already be possible to do, as Twitter is just a different provider type (string).  But we should add a second example to this method, that shows how to create a social provider (we could use twitter as the sample):

https://docs.stormpath.com/nodejs/jsdoc/Client.html#createDirectory__anchor
