### ISSUE TITLE
deprecate resource.customData.get()

### ISSUE THREAD

**Issue by robertjd** [stormpath/stormpath-sdk-node#99]
In release 1.0 we will remove the `resource.customData.get()` accessor for CustomData instances.  

Please use `resource.getCustomData()` instead.

We are changing this because it does not conform with our design for the SDK.  Our design paradigm is:

1) call a getter method for any reference to another Resource, and 
2) use direct property access for primitive (non-reference) properties directly attributed to the resource.

For that reason, having an object (with getter methods) directly attached to the parent resource is not correct and is, in fact, quite confusing - especially when dealing with resource expansions.

**Comment by rdegges** [comment]
@robertjd should we close this? Or is there more work to do before 1.0?

**Comment by rdegges** [comment]
Closing this as I'm merging it in.
